-- =====================================================
-- ORDER MODULE TEST SCHEMA - ORACLE
-- Dùng để test riêng module Giao dịch / Đơn hàng
-- =====================================================

-- =========================
-- 1. XÓA BẢNG CŨ NẾU CÓ
-- Chỉ chạy trong schema test cá nhân
-- =========================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LICHSUTRANGTHAIDH CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DANHGIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CHITIETDH CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DONHANG CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- =========================
-- 2. TẠO BẢNG ĐƠN HÀNG
-- =========================

CREATE TABLE DONHANG (
    MaDH NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    MaTK_KH NUMBER NOT NULL,
    MaTK_NV NUMBER,

    NgayDat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MaDC NUMBER,

    TongTienMon NUMBER(15, 2) NOT NULL,
    TienGiamGia NUMBER(15, 2) DEFAULT 0,
    ThanhTien NUMBER(15, 2) NOT NULL,

    TrangThaiDon VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,

    MaGG NUMBER,
    GhiChu CLOB,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT CK_DONHANG_TRANGTHAI CHECK (
        TrangThaiDon IN (
            'PENDING',
            'CONFIRMED',
            'SHIPPING',
            'DELIVERED',
            'CANCEL_REQUESTED',
            'CANCELLED'
        )
    )
);

-- =========================
-- 3. TẠO BẢNG CHI TIẾT ĐƠN HÀNG
-- =========================

CREATE TABLE CHITIETDH (
    MaDH NUMBER NOT NULL,
    MaMon NUMBER NOT NULL,

    TenMon VARCHAR2(100) NOT NULL,
    SoLuong NUMBER NOT NULL,
    DonGia NUMBER(15, 2) NOT NULL,
    ThanhTien NUMBER(15, 2) NOT NULL,

    CONSTRAINT PK_CHITIETDH PRIMARY KEY (MaDH, MaMon),

    CONSTRAINT FK_CHITIETDH_DONHANG
        FOREIGN KEY (MaDH)
        REFERENCES DONHANG(MaDH)
        ON DELETE CASCADE,

    CONSTRAINT CK_CHITIETDH_SOLUONG CHECK (SoLuong > 0)
);

-- =========================
-- 4. TẠO BẢNG ĐÁNH GIÁ
-- =========================

CREATE TABLE DANHGIA (
    MaDG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    MaTK_KH NUMBER NOT NULL,
    MaMon NUMBER NOT NULL,
    MaDH NUMBER NOT NULL,

    Sao NUMBER NOT NULL,
    NoiDung CLOB,
    NgayDG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_DANHGIA_DONHANG
        FOREIGN KEY (MaDH)
        REFERENCES DONHANG(MaDH)
        ON DELETE CASCADE,

    CONSTRAINT CK_DANHGIA_SAO CHECK (Sao BETWEEN 1 AND 5),

    CONSTRAINT UQ_DANHGIA_ORDER_MON_USER
        UNIQUE (MaDH, MaMon, MaTK_KH)
);

-- =====================================================
-- 5. THÊM DỮ LIỆU TEST
-- Quy ước:
-- MaTK_KH = 1 là khách hàng test
-- MaTK_NV = 2 là nhân viên test
-- MaDC = 1 là địa chỉ test
-- MaMon = 1, 2, 3 là món ăn test
-- =====================================================

-- =========================
-- DATA TEST MODULE ORDER
-- =========================

-- 1. Vai trò
INSERT INTO VAITRO (MaVT, TenVT)
VALUES ('CUSTOMER', 'Khách hàng');

INSERT INTO VAITRO (MaVT, TenVT)
VALUES ('STAFF', 'Nhân viên');

-- 2. Người dùng
-- Nếu bảng của bạn là USERS thì đổi "USER" thành USERS.
INSERT INTO "USER" (Password, HoTen, SDT, Email, TrangThai, MaVT)
VALUES ('123456', 'Nguyễn Bảo Ái Vy', '0901000001', 'aivy@example.com', 'ACTIVE', 'CUSTOMER');

INSERT INTO "USER" (Password, HoTen, SDT, Email, TrangThai, MaVT)
VALUES ('123456', 'Trần Minh Đức', '0901000002', 'ducstaff@example.com', 'ACTIVE', 'STAFF');

-- 3. Địa chỉ khách hàng
INSERT INTO DIACHI (
    MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan,
    DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault
)
VALUES (
    1, 'Nhà riêng', 'Nguyễn Bảo Ái Vy', '0901000001',
    '123 Nguyễn Huệ', 'TP. Hồ Chí Minh', 'Quận 1', 'Bến Nghé', 1
);

-- 4. Danh mục
INSERT INTO DANHMUC (TenDM, MoTa, image_url, IsAvailable)
VALUES ('Burger', 'Các món burger bán chạy', '/images/category/burger.png', 1);

INSERT INTO DANHMUC (TenDM, MoTa, image_url, IsAvailable)
VALUES ('Gà rán', 'Các món gà rán và combo', '/images/category/chicken.png', 1);

-- 5. Món ăn
INSERT INTO MONAN (TenMon, MoTa, Gia, SLuongTon, SLuongDaBan, MaDM, GiaGiam, image_url, IsAvailable)
VALUES ('Burger Bò Phô Mai', 'Burger bò kèm phô mai và sốt đặc biệt', 45000, 100, 20, 1, 0, '/images/food/burger-bo-pho-mai.png', 1);

INSERT INTO MONAN (TenMon, MoTa, Gia, SLuongTon, SLuongDaBan, MaDM, GiaGiam, image_url, IsAvailable)
VALUES ('Gà Rán Giòn Cay', 'Miếng gà rán giòn vị cay nhẹ', 39000, 100, 30, 2, 0, '/images/food/ga-ran-gion-cay.png', 1);

-- 6. Phương thức thanh toán
INSERT INTO PHUONGTHUCTT (MaPT, TenPT)
VALUES ('COD', 'Thanh toán khi nhận hàng');

INSERT INTO PHUONGTHUCTT (MaPT, TenPT)
VALUES ('BANK', 'Chuyển khoản ngân hàng');

-- 7. Đơn hàng test 1: PENDING để test hủy trực tiếp
INSERT INTO DONHANG (
    MaTK_KH, MaTK_NV, NgayDat, MaDC,
    TongTienMon, TienGiamGia, ThanhTien,
    TrangThaiDon, MaGG, GhiChu
)
VALUES (
    1, NULL, CURRENT_TIMESTAMP, 1,
    90000, 0, 90000,
    'PENDING', NULL, 'Đơn test trạng thái PENDING'
);

INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien)
VALUES (1, 1, 'Burger Bò Phô Mai', 2, 45000, 90000);

INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT)
VALUES (1, 'COD', CURRENT_TIMESTAMP, 90000, 'Pending');

-- 8. Đơn hàng test 2: CONFIRMED để test yêu cầu hủy
INSERT INTO DONHANG (
    MaTK_KH, MaTK_NV, NgayDat, MaDC,
    TongTienMon, TienGiamGia, ThanhTien,
    TrangThaiDon, MaGG, GhiChu
)
VALUES (
    1, 2, CURRENT_TIMESTAMP, 1,
    84000, 0, 84000,
    'CONFIRMED', NULL, 'Đơn test trạng thái CONFIRMED'
);

INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien)
VALUES (2, 2, 'Gà Rán Giòn Cay', 2, 42000, 84000);

INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT)
VALUES (2, 'COD', CURRENT_TIMESTAMP, 84000, 'Pending');

-- 9. Đơn hàng test 3: SHIPPING để test xác nhận đã nhận hàng
INSERT INTO DONHANG (
    MaTK_KH, MaTK_NV, NgayDat, MaDC,
    TongTienMon, TienGiamGia, ThanhTien,
    TrangThaiDon, MaGG, GhiChu
)
VALUES (
    1, 2, CURRENT_TIMESTAMP, 1,
    123000, 0, 123000,
    'SHIPPING', NULL, 'Đơn test trạng thái SHIPPING'
);

INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien)
VALUES (3, 1, 'Burger Bò Phô Mai', 1, 45000, 45000);

INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien)
VALUES (3, 2, 'Gà Rán Giòn Cay', 2, 39000, 78000);

INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT)
VALUES (3, 'COD', CURRENT_TIMESTAMP, 123000, 'Pending');

-- 10. Đơn hàng test 4: DELIVERED để test đánh giá
INSERT INTO DONHANG (
    MaTK_KH, MaTK_NV, NgayDat, MaDC,
    TongTienMon, TienGiamGia, ThanhTien,
    TrangThaiDon, MaGG, GhiChu
)
VALUES (
    1, 2, CURRENT_TIMESTAMP, 1,
    45000, 0, 45000,
    'DELIVERED', NULL, 'Đơn test trạng thái DELIVERED'
);

INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien)
VALUES (4, 1, 'Burger Bò Phô Mai', 1, 45000, 45000);

INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT)
VALUES (4, 'COD', CURRENT_TIMESTAMP, 45000, 'Paid');

COMMIT;

-- Đơn 1: PENDING - dùng để test khách hủy trực tiếp
INSERT INTO DONHANG (
    MaTK_KH,
    MaTK_NV,
    NgayDat,
    MaDC,
    TongTienMon,
    TienGiamGia,
    ThanhTien,
    TrangThaiDon,
    MaGG,
    GhiChu
)
VALUES (
    1,
    NULL,
    CURRENT_TIMESTAMP,
    1,
    90000,
    0,
    90000,
    'PENDING',
    NULL,
    'Đơn test PENDING - khách được hủy trực tiếp'
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    1,
    1,
    'Burger Bò Phô Mai',
    2,
    45000,
    90000
);

-- Đơn 2: CONFIRMED - dùng để test gửi yêu cầu hủy
INSERT INTO DONHANG (
    MaTK_KH,
    MaTK_NV,
    NgayDat,
    MaDC,
    TongTienMon,
    TienGiamGia,
    ThanhTien,
    TrangThaiDon,
    MaGG,
    GhiChu
)
VALUES (
    1,
    2,
    CURRENT_TIMESTAMP,
    1,
    78000,
    0,
    78000,
    'CONFIRMED',
    NULL,
    'Đơn test CONFIRMED - khách chỉ được gửi yêu cầu hủy'
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    2,
    2,
    'Gà Rán Giòn Cay',
    2,
    39000,
    78000
);

-- Đơn 3: SHIPPING - dùng để test xác nhận đã nhận hàng
INSERT INTO DONHANG (
    MaTK_KH,
    MaTK_NV,
    NgayDat,
    MaDC,
    TongTienMon,
    TienGiamGia,
    ThanhTien,
    TrangThaiDon,
    MaGG,
    GhiChu
)
VALUES (
    1,
    2,
    CURRENT_TIMESTAMP,
    1,
    123000,
    0,
    123000,
    'SHIPPING',
    NULL,
    'Đơn test SHIPPING - khách có thể xác nhận đã nhận hàng'
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    3,
    1,
    'Burger Bò Phô Mai',
    1,
    45000,
    45000
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    3,
    2,
    'Gà Rán Giòn Cay',
    2,
    39000,
    78000
);

-- Đơn 4: DELIVERED - dùng để test đánh giá
INSERT INTO DONHANG (
    MaTK_KH,
    MaTK_NV,
    NgayDat,
    MaDC,
    TongTienMon,
    TienGiamGia,
    ThanhTien,
    TrangThaiDon,
    MaGG,
    GhiChu
)
VALUES (
    1,
    2,
    CURRENT_TIMESTAMP,
    1,
    45000,
    0,
    45000,
    'DELIVERED',
    NULL,
    'Đơn test DELIVERED - khách được đánh giá món ăn'
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    4,
    1,
    'Burger Bò Phô Mai',
    1,
    45000,
    45000
);

-- Đơn 5: CANCELLED - dùng để test đơn đã hủy
INSERT INTO DONHANG (
    MaTK_KH,
    MaTK_NV,
    NgayDat,
    MaDC,
    TongTienMon,
    TienGiamGia,
    ThanhTien,
    TrangThaiDon,
    MaGG,
    GhiChu
)
VALUES (
    1,
    NULL,
    CURRENT_TIMESTAMP,
    1,
    59000,
    0,
    59000,
    'CANCELLED',
    NULL,
    'Đơn test CANCELLED - không được thao tác thêm'
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    5,
    3,
    'Khoai Tây Chiên Lắc Phô Mai',
    1,
    59000,
    59000
);

-- Đơn 6: DELIVERED nhiều món - dùng để test đánh giá từng món
INSERT INTO DONHANG (
    MaTK_KH,
    MaTK_NV,
    NgayDat,
    MaDC,
    TongTienMon,
    TienGiamGia,
    ThanhTien,
    TrangThaiDon,
    MaGG,
    GhiChu
)
VALUES (
    1,
    2,
    CURRENT_TIMESTAMP,
    1,
    143000,
    10000,
    133000,
    'DELIVERED',
    NULL,
    'Đơn test DELIVERED nhiều món - test đánh giá từng món'
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    6,
    1,
    'Burger Bò Phô Mai',
    1,
    45000,
    45000
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    6,
    2,
    'Gà Rán Giòn Cay',
    2,
    39000,
    78000
);

INSERT INTO CHITIETDH (
    MaDH,
    MaMon,
    TenMon,
    SoLuong,
    DonGia,
    ThanhTien
)
VALUES (
    6,
    3,
    'Khoai Tây Chiên Lắc Phô Mai',
    1,
    20000,
    20000
);

COMMIT;

-- =====================================================
-- 6. KIỂM TRA DỮ LIỆU SAU KHI TẠO
-- =====================================================

SELECT MaDH, MaTK_KH, MaTK_NV, TrangThaiDon, ThanhTien, GhiChu
FROM DONHANG
ORDER BY MaDH;

SELECT MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien
FROM CHITIETDH
ORDER BY MaDH, MaMon;

SELECT MaTT, MaDH, MaPT, SoTien, TrangThaiTT
FROM THANHTOAN
ORDER BY MaTT DESC;

SELECT *
FROM CHITIETGH;

SELECT *
FROM DANHGIA
ORDER BY NgayDG DESC;

SELECT *
FROM GIOHANG;

SELECT *
FROM CHITIETGH
ORDER BY MaGH, MaMon;

DELETE FROM CHITIETGH;
DELETE FROM GIOHANG;

INSERT INTO GIOHANG (MaTK)
VALUES (1);

INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
VALUES (1, 1, 2);

INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
VALUES (1, 2, 1);

INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
VALUES (1, 3, 1);

COMMIT;

-- =========================
-- CART MODULE TEST TABLES
-- =========================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CHITIETGH CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GIOHANG CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE GIOHANG (
    MaGH NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTK NUMBER NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CHITIETGH (
    MaGH NUMBER NOT NULL,
    MaMon NUMBER NOT NULL,
    SLuong NUMBER DEFAULT 1 NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_CHITIETGH PRIMARY KEY (MaGH, MaMon),
    CONSTRAINT FK_CHITIETGH_GIOHANG
        FOREIGN KEY (MaGH)
        REFERENCES GIOHANG(MaGH)
        ON DELETE CASCADE,
    CONSTRAINT CK_CHITIETGH_SOLUONG CHECK (SLuong > 0)
);

-- Giỏ hàng test cho customerId = 1
INSERT INTO GIOHANG (MaTK)
VALUES (1);

-- MaGH = 1, MaMon = 1/2/3 tương ứng món test trong order_test_data.sql
INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
VALUES (1, 1, 2);

INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
VALUES (1, 2, 1);

INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
VALUES (1, 3, 1);

COMMIT;

SELECT *
FROM GIOHANG;

SELECT *
FROM CHITIETGH;

-- =========================
-- CHECKOUT TEST TABLES
-- =========================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE THANHTOAN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MAGIAMGIA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIACHI CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PHUONGTHUCTT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MONAN CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE MONAN (
    MaMon NUMBER PRIMARY KEY,
    TenMon VARCHAR2(100) NOT NULL,
    Gia NUMBER(15, 2) NOT NULL,
    SLuongTon NUMBER DEFAULT 100,
    IsAvailable NUMBER(1) DEFAULT 1
);

CREATE TABLE DIACHI (
    MaDC NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTK NUMBER NOT NULL,
    TenDiaChi VARCHAR2(100),
    TenNguoiNhan VARCHAR2(100),
    SDTNguoiNhan VARCHAR2(15),
    DiaChiCuThe VARCHAR2(255),
    TinhThanh VARCHAR2(50),
    QuanHuyen VARCHAR2(50),
    PhuongXa VARCHAR2(50),
    IsDefault NUMBER(1) DEFAULT 0
);

CREATE TABLE MAGIAMGIA (
    MaGG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaCode VARCHAR2(50) UNIQUE NOT NULL,
    LoaiGiam VARCHAR2(20) NOT NULL,
    MucGiam NUMBER(15, 2) NOT NULL,
    DieuKien NUMBER(15, 2) DEFAULT 0,
    NgayBatDau TIMESTAMP,
    NgayKetThuc TIMESTAMP,
    SoLanSuDung NUMBER DEFAULT 0,

    CONSTRAINT CK_MAGIAMGIA_LOAI CHECK (LoaiGiam IN ('PERCENT', 'AMOUNT'))
);

CREATE TABLE PHUONGTHUCTT (
    MaPT VARCHAR2(20) PRIMARY KEY,
    TenPT VARCHAR2(50) NOT NULL
);

CREATE TABLE THANHTOAN (
    MaTT NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDH NUMBER NOT NULL,
    MaPT VARCHAR2(20) NOT NULL,
    NgayTT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SoTien NUMBER(15, 2) NOT NULL,
    TrangThaiTT VARCHAR2(20) DEFAULT 'Pending',

    CONSTRAINT FK_THANHTOAN_DONHANG
        FOREIGN KEY (MaDH)
        REFERENCES DONHANG(MaDH)
        ON DELETE CASCADE,

    CONSTRAINT FK_THANHTOAN_PHUONGTHUCTT
        FOREIGN KEY (MaPT)
        REFERENCES PHUONGTHUCTT(MaPT)
);

INSERT INTO MONAN (MaMon, TenMon, Gia, SLuongTon, IsAvailable)
VALUES (1, 'Burger Bò Phô Mai', 45000, 100, 1);

INSERT INTO MONAN (MaMon, TenMon, Gia, SLuongTon, IsAvailable)
VALUES (2, 'Gà Rán Giòn Cay', 39000, 100, 1);

INSERT INTO MONAN (MaMon, TenMon, Gia, SLuongTon, IsAvailable)
VALUES (3, 'Khoai Tây Chiên Lắc Phô Mai', 20000, 100, 1);

INSERT INTO DIACHI (
    MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan,
    DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault
)
VALUES (
    1, 'Nhà riêng', 'Nguyễn Bảo Ái Vy', '0901000001',
    '123 Nguyễn Huệ', 'TP. Hồ Chí Minh', 'Quận 1', 'Bến Nghé', 1
);

INSERT INTO MAGIAMGIA (
    MaCode, LoaiGiam, MucGiam, DieuKien,
    NgayBatDau, NgayKetThuc, SoLanSuDung
)
VALUES (
    'JOLLI10', 'PERCENT', 10, 50000,
    CURRENT_TIMESTAMP - INTERVAL '1' DAY,
    CURRENT_TIMESTAMP + INTERVAL '30' DAY,
    0
);

INSERT INTO MAGIAMGIA (
    MaCode, LoaiGiam, MucGiam, DieuKien,
    NgayBatDau, NgayKetThuc, SoLanSuDung
)
VALUES (
    'FREESHIP20', 'AMOUNT', 20000, 80000,
    CURRENT_TIMESTAMP - INTERVAL '1' DAY,
    CURRENT_TIMESTAMP + INTERVAL '30' DAY,
    0
);

INSERT INTO PHUONGTHUCTT (MaPT, TenPT)
VALUES ('COD', 'Thanh toán khi nhận hàng');

INSERT INTO PHUONGTHUCTT (MaPT, TenPT)
VALUES ('BANK', 'Chuyển khoản ngân hàng');

INSERT INTO PHUONGTHUCTT (MaPT, TenPT)
VALUES ('EWALLET', 'Ví điện tử');

COMMIT;

ALTER TABLE MONAN ADD image_url VARCHAR2(255);

UPDATE MONAN
SET image_url = 'https://static.kfcvietnam.com.vn/images/items/lg/6-COB-April.jpg?v=3ydVxg'
WHERE MaMon = 1;

COMMIT;

INSERT INTO PHUONGTHUCTT (MaPT, TenPT)
VALUES ('CREDIT_CARD', 'Thẻ tín dụng / Ghi nợ');

COMMIT;

SELECT *
FROM PHUONGTHUCTT;

-----

DELETE FROM CHITIETGH
WHERE MaGH IN (
    SELECT MaGH
    FROM GIOHANG
    WHERE MaTK = 1
);

DELETE FROM GIOHANG
WHERE MaTK = 1;

COMMIT;

DECLARE
    v_MaGH NUMBER;
BEGIN
    INSERT INTO GIOHANG (MaTK)
    VALUES (1)
    RETURNING MaGH INTO v_MaGH;

    INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
    VALUES (v_MaGH, 1, 2);

    INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
    VALUES (v_MaGH, 2, 1);

    INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
    VALUES (v_MaGH, 3, 1);

    COMMIT;
END;
/

SELECT * FROM GIOHANG;
SELECT * FROM CHITIETGH ORDER BY MaGH, MaMon;

INSERT INTO DIACHI (
    MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan,
    DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault
)
VALUES (
    1, 'Nhà phụ', 'Trần Thị B', '0987654321',
    '456 Đường Số 4', 'TP.Hồ Chí Minh', 'Quận 6', 'Phường 5', 0
);

INSERT INTO DIACHI (
    MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan,
    DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault
)
VALUES (
    1, 'Công ty', 'Lê Văn C', '0909090909',
    '789 Đường Láng', 'Hà Nội', 'Đống Đa', 'Láng Thượng', 0
);

COMMIT;

----
----
-- =========================================
-- RESET GIỎ HÀNG TEST CHO CUSTOMER ID = 1
-- =========================================

-- Xóa chi tiết giỏ hàng cũ của khách 1
DELETE FROM CHITIETGH
WHERE MaGH IN (
    SELECT MaGH
    FROM GIOHANG
    WHERE MaTK = 1
);

-- Xóa giỏ hàng cũ của khách 1
DELETE FROM GIOHANG
WHERE MaTK = 1;

COMMIT;

-- Tạo lại giỏ hàng mới và thêm món test
DECLARE
    v_MaGH NUMBER;
BEGIN
    INSERT INTO GIOHANG (MaTK)
    VALUES (1)
    RETURNING MaGH INTO v_MaGH;

    INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
    VALUES (v_MaGH, 1, 2);

    INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
    VALUES (v_MaGH, 2, 1);

    INSERT INTO CHITIETGH (MaGH, MaMon, SLuong)
    VALUES (v_MaGH, 3, 1);

    COMMIT;
END;
/


SELECT *
FROM GIOHANG
WHERE MaTK = 1;

SELECT *
FROM CHITIETGH
ORDER BY MaGH, MaMon;

-- Xóa bảng cũ nếu có
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE "USER" CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VAITRO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Tạo bảng vai trò
CREATE TABLE VAITRO (
    MaVT NUMBER PRIMARY KEY,
    TenVT VARCHAR2(50) NOT NULL
);

-- Tạo bảng user
CREATE TABLE "USER" (
    MaTK NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Password VARCHAR2(255) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    HoTen VARCHAR2(100) NOT NULL,
    SDT VARCHAR2(20),
    TrangThai VARCHAR2(20) DEFAULT 'ACTIVE',
    MaVT NUMBER NOT NULL,
    CONSTRAINT FK_USER_VAITRO FOREIGN KEY (MaVT) REFERENCES VAITRO(MaVT)
);

-- Thêm vai trò
INSERT INTO VAITRO (MaVT, TenVT) VALUES (1, 'CLIENT');
INSERT INTO VAITRO (MaVT, TenVT) VALUES (2, 'STAFF');
INSERT INTO VAITRO (MaVT, TenVT) VALUES (3, 'MANAGER');
INSERT INTO VAITRO (MaVT, TenVT) VALUES (4, 'ADMIN');

-- Password BCrypt cho mật khẩu gốc: 123456
INSERT INTO "USER" (Password, Email, HoTen, SDT, TrangThai, MaVT)
VALUES ('$2a$10$N4vL5RcLp3TgCOvlYi90w5huS.YavR922zHw1WhfchxgPw1Mq.e', 'user1@fastfood.vn', 'User A', '090000001', 'ACTIVE', 1);

INSERT INTO "USER" (Password, Email, HoTen, SDT, TrangThai, MaVT)
VALUES ('$2a$10$N4vL5RcLp3TgCOvlYi90w5huS.YavR922zHw1WhfchxgPw1Mq.e', 'user2@fastfood.vn', 'User B', '090000002', 'ACTIVE', 2);

INSERT INTO "USER" (Password, Email, HoTen, SDT, TrangThai, MaVT)
VALUES ('$2a$10$N4vL5RcLp3TgCOvlYi90w5huS.YavR922zHw1WhfchxgPw1Mq.e', 'user3@fastfood.vn', 'User C', '090000003', 'ACTIVE', 3);

INSERT INTO "USER" (Password, Email, HoTen, SDT, TrangThai, MaVT)
VALUES ('$2a$10$N4vL5RcLp3TgCOvlYi90w5huS.YavR922zHw1WhfchxgPw1Mq.e', 'user4@fastfood.vn', 'User D', '090000004', 'ACTIVE', 4);

COMMIT;


SELECT MaVT, TenVT
FROM VAITRO
ORDER BY MaVT;

SELECT MaTK, Email, HoTen, SDT, TrangThai, MaVT
FROM "USER"
ORDER BY MaTK;



-- ================================
-- CREATE VAITRO + USERS FOR LOGIN
-- ================================

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE VAITRO (
        MaVT NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        TenVT VARCHAR2(50) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE USERS (
        MaTK NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        Password VARCHAR2(255) NOT NULL,
        HoTen VARCHAR2(100) NOT NULL,
        SDT VARCHAR2(15),
        Email VARCHAR2(100) NOT NULL UNIQUE,
        TrangThai VARCHAR2(50),
        MaVT NUMBER,
        created_at TIMESTAMP,
        updated_at TIMESTAMP,
        CONSTRAINT FK_USERS_VAITRO FOREIGN KEY (MaVT) REFERENCES VAITRO(MaVT)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/



MERGE INTO VAITRO v
USING (
    SELECT 1 AS MaVT, 'CLIENT' AS TenVT FROM dual
    UNION ALL
    SELECT 2, 'STAFF' FROM dual
    UNION ALL
    SELECT 3, 'MANAGER' FROM dual
    UNION ALL
    SELECT 4, 'ADMIN' FROM dual
) src
ON (v.MaVT = src.MaVT)
WHEN MATCHED THEN
    UPDATE SET v.TenVT = src.TenVT
WHEN NOT MATCHED THEN
    INSERT (MaVT, TenVT)
    VALUES (src.MaVT, src.TenVT);

COMMIT;


MERGE INTO USERS u
USING (
    SELECT 
        'user1@fastfood.vn' AS Email,
        'User A' AS HoTen,
        '090000001' AS SDT,
        'ACTIVE' AS TrangThai,
        1 AS MaVT
    FROM dual
    UNION ALL
    SELECT 'user2@fastfood.vn', 'User B', '090000002', 'ACTIVE', 2 FROM dual
    UNION ALL
    SELECT 'user3@fastfood.vn', 'User C', '090000003', 'ACTIVE', 3 FROM dual
    UNION ALL
    SELECT 'user4@fastfood.vn', 'User D', '090000004', 'ACTIVE', 4 FROM dual
) src
ON (u.Email = src.Email)
WHEN MATCHED THEN
    UPDATE SET 
        u.HoTen = src.HoTen,
        u.SDT = src.SDT,
        u.TrangThai = src.TrangThai,
        u.MaVT = src.MaVT,
        u.Password = '$2a$10$N4vL5RcLp3TgCOvlYi90w5huS.YavR922zHw1WhfchxgPw1Mq.e'
WHEN NOT MATCHED THEN
    INSERT (Password, Email, HoTen, SDT, TrangThai, MaVT, created_at, updated_at)
    VALUES (
        '$2a$10$N4vL5RcLp3TgCOvlYi90w5huS.YavR922zHw1WhfchxgPw1Mq.e',
        src.Email,
        src.HoTen,
        src.SDT,
        src.TrangThai,
        src.MaVT,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

COMMIT;

SELECT MaVT, TenVT
FROM VAITRO
ORDER BY MaVT;

SELECT MaTK, Email, HoTen, SDT, TrangThai, MaVT
FROM USERS
ORDER BY MaTK;


SELECT table_name
FROM user_tables
WHERE table_name IN ('USERS', 'VAITRO');

SELECT MaTK, Email, HoTen, SDT, TrangThai, MaVT
FROM USERS
ORDER BY MaTK;

SELECT MaVT, TenVT
FROM VAITRO
ORDER BY MaVT;

SELECT u.MaTK, u.Email, u.HoTen, u.TrangThai, u.MaVT, v.TenVT
FROM USERS u
LEFT JOIN VAITRO v ON u.MaVT = v.MaVT
WHERE LOWER(u.Email) = LOWER('user2@fastfood.vn');


SELECT column_name
FROM user_tab_columns
WHERE table_name = 'DONHANG'
ORDER BY column_id;

SELECT column_name
FROM user_tab_columns
WHERE table_name = 'USERS'
ORDER BY column_id;

SELECT column_name
FROM user_tab_columns
WHERE table_name = 'DIACHI'
ORDER BY column_id;

SELECT column_name
FROM user_tab_columns
WHERE table_name = 'THANHTOAN'
ORDER BY column_id;

SELECT column_name
FROM user_tab_columns
WHERE table_name = 'CHITIETDH'
ORDER BY column_id;

SELECT MaDH, TrangThaiDon, MaTK_NV, GhiChu
FROM DONHANG
WHERE MaDH = 15;

CREATE TABLE LICHSUTRANGTHAIDH (
    MaLS NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    MaDH NUMBER NOT NULL,

    TrangThaiCu VARCHAR2(30),
    TrangThaiMoi VARCHAR2(30) NOT NULL,

    NguoiThucHienLoai VARCHAR2(20) DEFAULT 'SYSTEM' NOT NULL,
    MaNguoiThucHien NUMBER,

    LyDo CLOB,
    ThoiGian TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_LSTT_DONHANG
        FOREIGN KEY (MaDH)
        REFERENCES DONHANG(MaDH)
        ON DELETE CASCADE,

    CONSTRAINT CK_LSTT_TRANGTHAI_MOI CHECK (
        TrangThaiMoi IN (
            'PENDING',
            'CONFIRMED',
            'SHIPPING',
            'DELIVERED',
            'CANCEL_REQUESTED',
            'CANCELLED'
        )
    ),

    CONSTRAINT CK_LSTT_NGUOI_THUC_HIEN CHECK (
        NguoiThucHienLoai IN (
            'CUSTOMER',
            'STAFF',
            'MANAGER',
            'ADMIN',
            'SYSTEM'
        )
    )
);

CREATE INDEX IDX_LSTT_DONHANG_TIME
ON LICHSUTRANGTHAIDH (MaDH, ThoiGian);

INSERT INTO LICHSUTRANGTHAIDH (
    MaDH,
    TrangThaiCu,
    TrangThaiMoi,
    NguoiThucHienLoai,
    MaNguoiThucHien,
    LyDo,
    ThoiGian
)
SELECT
    MaDH,
    'PENDING',
    TrangThaiDon,
    CASE
        WHEN TrangThaiDon = 'CANCELLED' AND MaTK_NV IS NULL THEN 'CUSTOMER'
        WHEN MaTK_NV IS NOT NULL THEN 'STAFF'
        ELSE 'SYSTEM'
    END,
    CASE
        WHEN MaTK_NV IS NOT NULL THEN MaTK_NV
        ELSE MaTK_KH
    END,
    'Bổ sung trạng thái hiện tại từ dữ liệu cũ',
    CURRENT_TIMESTAMP
FROM DONHANG d
WHERE TrangThaiDon <> 'PENDING'
AND NOT EXISTS (
    SELECT 1
    FROM LICHSUTRANGTHAIDH ls
    WHERE ls.MaDH = d.MaDH
    AND ls.TrangThaiMoi = d.TrangThaiDon
);
