ALTER SESSION SET CONTAINER = orclpdb;
BEGIN
  EXECUTE IMMEDIATE 'DROP USER fastfooddb CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1918 THEN
      RAISE;
    END IF;
END;
/
CREATE USER fastfooddb IDENTIFIED BY "123456"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO fastfooddb;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO fastfooddb;
exit
