# Database MySQL Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/ORCLPDB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=fastfooddb
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cho phép chạy data.sql với Oracle (non-embedded DB)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true


