INSERT INTO VAITRO (TenVT) VALUES ('CLIENT');
INSERT INTO VAITRO (TenVT) VALUES ('STAFF');
INSERT INTO VAITRO (TenVT) VALUES ('MANAGER');
INSERT INTO VAITRO (TenVT) VALUES ('ADMIN');

-- Tài khoản mẫu với mật khẩu 123456
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user1@fastfood.vn', 'User A', '0900000001', 'ACTIVE', 1);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user2@fastfood.vn', 'User B', '0900000002', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user3@fastfood.vn', 'User C', '0900000003', 'ACTIVE', 3);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user4@fastfood.vn', 'User D', '0900000004', 'ACTIVE', 4);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user5@fastfood.vn', 'User E', '0900000005', 'BANNED', 1);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user6@fastfood.vn', 'User F', '0900000006', 'ACTIVE', 1);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user7@fastfood.vn', 'User G', '0900000007', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user8@fastfood.vn', 'User H', '0900000008', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user9@fastfood.vn', 'User I', '0900000009', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user10@fastfood.vn', 'User J', '0900000010', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user11@fastfood.vn', 'User K', '0900000011', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user12@fastfood.vn', 'User L', '0900000012', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user13@fastfood.vn', 'User M', '0900000013', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user14@fastfood.vn', 'User N', '0900000014', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user15@fastfood.vn', 'User O', '0900000015', 'BANNED', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user16@fastfood.vn', 'User P', '0900000016', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user17@fastfood.vn', 'User Q', '0900000017', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user18@fastfood.vn', 'User R', '0900000018', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user19@fastfood.vn', 'User S', '0900000019', 'ACTIVE', 2);
INSERT INTO NGUOIDUNG (Password, Email, HoTen, SDT, TrangThai, MaVT) VALUES ('$2a$12$3iN4vL5Rclp3TgCOvlYi9Ow5huS.YavR922zHw1WhfchxgPwlMq.e', 'user20@fastfood.vn', 'User T', '0900000020', 'ACTIVE', 2);

COMMIT;

INSERT INTO DANHMUC (TenDM, MoTa, isAvailable, created_at, updated_at) VALUES (N'Gà rán', N'Những món gà rán giòn rụm, đậm vị và dễ ăn.', 1, SYSDATE, SYSDATE);
INSERT INTO DANHMUC (TenDM, MoTa, isAvailable, created_at, updated_at) VALUES (N'Burger', N'Burger nóng hổi với phần nhân đầy đặn, hợp cho bữa ăn nhanh.', 1, SYSDATE, SYSDATE);
INSERT INTO DANHMUC (TenDM, MoTa, isAvailable, created_at, updated_at) VALUES (N'Mì Ý', N'Mì Ý sốt đậm đà, dễ ăn và vừa miệng.', 1, SYSDATE, SYSDATE);
INSERT INTO DANHMUC (TenDM, MoTa, isAvailable, created_at, updated_at) VALUES (N'Đồ ăn kèm', N'Những món ăn kèm giúp bữa ăn tròn vị hơn.', 1, SYSDATE, SYSDATE);
INSERT INTO DANHMUC (TenDM, MoTa, isAvailable, created_at, updated_at) VALUES (N'Thức uống', N'Thức uống mát lạnh, dễ kết hợp với nhiều món chính.', 1, SYSDATE, SYSDATE);
INSERT INTO DANHMUC (TenDM, MoTa, isAvailable, created_at, updated_at) VALUES (N'Tráng miệng', N'Các món ngọt nhẹ để khép lại bữa ăn.', 1, SYSDATE, SYSDATE);
COMMIT;

INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Gà Rán Giòn Cay', N'Phần gà rán giòn rụm, thấm vị cay nhẹ vừa ăn, bên trong vẫn mềm và mọng nước.', 38000, 'GaRan_GionCay.png', 1, 1, 452, 85, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Gà Rán Truyền Thống', N'Gà rán vị truyền thống với lớp da giòn mỏng, thịt bên trong thơm và giữ được độ ngọt tự nhiên.', 36000, 'GaRan_TruyenThong.png', 1, 1, 380, 60, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Gà Phủ Sốt Phô Mai', N'Gà rán phủ sốt phô mai béo mịn, thơm đậm vị, ăn là thấy rõ độ cuốn.', 42000, 'GaRan_PhoMai.png', 1, 1, 215, 40, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Gà Sốt Cay Ngọt Hàn Quốc', N'Gà rán áo sốt cay ngọt đậm đà, vị nổi bật nhưng vẫn dễ ăn, hợp cho bữa đổi vị.', 42000, 'GaRan_CayNgot.png', 1, 1, 189, 55, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Gà Popcorn', N'Những miếng gà nhỏ vừa miệng, giòn vui tai, rất hợp để ăn vặt hoặc gọi thêm cho đỡ thèm.', 35000, 'Ga_Popcorn.png', 1, 1, 275, 90, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Burger Bò Phô Mai', N'Burger bò phô mai với phần nhân đầy đặn, bánh mềm, vị đậm vừa phải và dễ ăn.', 45000, 'Burger_Bo.png', 2, 1, 310, 45, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Burger Gà Giòn Cay', N'Burger kẹp gà chiên giòn cay, thêm sốt béo nhẹ và rau tươi để cân vị.', 40000, 'Burger_Ga.png', 2, 1, 195, 50, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Burger Cá Tartar', N'Burger cá với lớp áo giòn nhẹ, ăn cùng sốt tartar chua thanh nên không bị ngấy.', 45000, 'Burger_Ca.png', 2, 1, 85, 30, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Burger Bò Gấp Đôi', N'Burger bò gấp đôi dành cho hôm muốn ăn thật no, nhân dày, phô mai rõ vị và khá đã miệng.', 65000, 'Burger_2Bo.png', 2, 1, 120, 25, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Mì Ý Sốt Bò Bằm', N'Mì Ý sốt bò bằm đậm đà, sợi mì vừa chín tới, hợp cho bữa ăn nhanh nhưng vẫn đủ vị.', 40000, 'MyY_Bo.png', 3, 1, 240, 65, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Mì Ý Xúc Xích', N'Mì Ý sốt cà chua ăn kèm xúc xích, hương vị quen thuộc, dễ ăn với cả người lớn lẫn trẻ nhỏ.', 35000, 'MyY_XucXich.png', 3, 1, 160, 40, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Khoai Tây Chiên (Vừa)', N'Khoai tây chiên vàng giòn, phần vừa đủ để ăn kèm burger hay gà rán.', 20000, 'KhoaiChien.png', 4, 1, 512, 120, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Khoai Tây Lắc Phô Mai', N'Khoai tây chiên lắc phô mai thơm nhẹ, vị mặn ngọt hài hòa, ăn rất bắt miệng.', 28000, 'KhoaiLac.png', 4, 1, 340, 80, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Salad Bắp Cải Dưa Tươi', N'Salad bắp cải trộn sốt chua ngọt nhẹ, giúp bữa ăn cân bằng và đỡ ngấy hơn.', 15000, 'Salad.png', 4, 1, 95, 35, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Trà Chanh Hạt Chia', N'Trà chanh mát lạnh pha vừa vị, thêm hạt chia để thức uống trông hấp dẫn hơn.', 20000, 'Chanh.png', 5, 1, 210, 60, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Nước Ép Xoài Đào', N'Nước ép xoài đào có vị trái cây rõ, thơm mát và dễ uống trong mọi khung giờ.', 20000, 'XoaiDao.png', 5, 1, 145, 45, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Pepsi', N'Nước ngọt có ga quen thuộc, uống lạnh sẽ hợp hơn khi dùng kèm món chiên.', 12000, 'Pepsi.png', 5, 1, 630, 200, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Mirinda', N'Nước ngọt vị cam tươi, dễ uống và hợp để gọi thêm cho combo.', 12000, 'Mirinda.png', 5, 1, 180, 150, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'7Up', N'Nước ngọt hương chanh mát, vị nhẹ, giúp bữa ăn thêm cân bằng.', 12000, '7Up.png', 5, 1, 250, 180, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Cacao Sữa Đá', N'Cacao sữa đá thơm đậm vị, ngọt vừa và phù hợp với ai thích đồ uống béo nhẹ.', 20000, 'Cacao.png', 5, 1, 110, 50, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Nước Suối', N'Nước suối đóng chai tiện lợi, lựa chọn đơn giản cho bữa ăn gọn gàng.', 8000, 'Nuoc.png', 5, 1, 420, 100, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Bánh Xoài Đào', N'Bánh xoài đào với lớp vỏ giòn, nhân trái cây ngọt dịu, ăn lúc còn ấm sẽ ngon hơn.', 15000, 'Banh_XoaiDao.png', 6, 1, 165, 55, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Tropical Sundae', N'Kem sundae phủ sốt trái cây nhiệt đới, vị mát và khá dễ ăn sau bữa chính.', 20000, 'Tropical_Sundae.png', 6, 1, 85, 30, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Kem Sundae Dâu', N'Kem sundae dâu mát lạnh, vị dâu chua nhẹ giúp món không bị quá ngọt.', 15000, 'Sundae_Dau.png', 6, 1, 190, 40, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Kem Sundae Socola', N'Kem sundae sốt socola béo thơm, hợp cho lúc muốn tráng miệng nhanh gọn.', 15000, 'Sundae_Socola.png', 6, 1, 220, 45, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Kem Socola (Cúp)', N'Kem socola cốc nhỏ, vị quen thuộc, tiện ăn và hợp túi tiền.', 7000, 'Kem_Socola.png', 6, 1, 315, 70, SYSDATE, SYSDATE);
INSERT INTO MONAN (TenMon, MoTa, Gia, image_url, MaDM, IsAvailable, SoLuongDaBan, SoLuongTon, created_at, updated_at) VALUES (N'Kem Sữa Tươi (Cúp)', N'Kem sữa tươi cốc nhỏ, mềm mịn và ngọt dịu, hợp để kết bữa nhẹ nhàng.', 5000, 'Kem.png', 6, 1, 480, 110, SYSDATE, SYSDATE);
COMMIT;

INSERT INTO DIACHI (MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan, DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault) VALUES (1, 'Nha rieng', 'Nguyen Bao Ai Vy', '0901000001', '123 Nguyen Hue', 'TP. Ho Chi Minh', 'Quan 1', 'Ben Nghe', 1);
INSERT INTO DIACHI (MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan, DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault) VALUES (1, 'Nha phu', 'Nguyen Bao Ai Vy', '0901000001', '456 Le Van Sy', 'TP. Ho Chi Minh', 'Quan 3', 'Phuong 12', 0);
INSERT INTO DIACHI (MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan, DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault) VALUES (1, 'Cong ty', 'Nguyen Bao Ai Vy', '0901000001', '789 Nguyen Van Linh', 'TP. Ho Chi Minh', 'Quan 7', 'Tan Phong', 0);
INSERT INTO DIACHI (MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan, DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault) VALUES (1, 'Nha ban', 'Tran Thi Bao Chau', '0912000001', '22 Cach Mang Thang 8', 'TP. Ho Chi Minh', 'Quan 10', 'Phuong 5', 0);
INSERT INTO DIACHI (MaTK, TenDiaChi, TenNguoiNhan, SDTNguoiNhan, DiaChiCuThe, TinhThanh, QuanHuyen, PhuongXa, IsDefault) VALUES (1, 'Ky tuc xa', 'Nguyen Bao Ai Vy', '0901000001', 'KTX Khu B', 'TP. Ho Chi Minh', 'Di An', 'Dong Hoa', 0);

INSERT INTO MAGIAMGIA (MaCode, LoaiGiam, MucGiam, DieuKien, NgayBatDau, NgayKetThuc, SoLanSuDung) VALUES ('JOLLI10', 'PERCENT', 10, 50000, CURRENT_TIMESTAMP - INTERVAL '1' DAY, CURRENT_TIMESTAMP + INTERVAL '30' DAY, 0);
INSERT INTO MAGIAMGIA (MaCode, LoaiGiam, MucGiam, DieuKien, NgayBatDau, NgayKetThuc, SoLanSuDung) VALUES ('FREESHIP20', 'AMOUNT', 20000, 80000, CURRENT_TIMESTAMP - INTERVAL '1' DAY, CURRENT_TIMESTAMP + INTERVAL '30' DAY, 0);
INSERT INTO MAGIAMGIA (MaCode, LoaiGiam, MucGiam, DieuKien, NgayBatDau, NgayKetThuc, SoLanSuDung) VALUES ('COMBO15', 'PERCENT', 15, 120000, CURRENT_TIMESTAMP - INTERVAL '1' DAY, CURRENT_TIMESTAMP + INTERVAL '20' DAY, 0);
INSERT INTO MAGIAMGIA (MaCode, LoaiGiam, MucGiam, DieuKien, NgayBatDau, NgayKetThuc, SoLanSuDung) VALUES ('SAVE30K', 'AMOUNT', 30000, 150000, CURRENT_TIMESTAMP - INTERVAL '1' DAY, CURRENT_TIMESTAMP + INTERVAL '15' DAY, 0);
INSERT INTO MAGIAMGIA (MaCode, LoaiGiam, MucGiam, DieuKien, NgayBatDau, NgayKetThuc, SoLanSuDung) VALUES ('VIP25', 'PERCENT', 25, 250000, CURRENT_TIMESTAMP - INTERVAL '1' DAY, CURRENT_TIMESTAMP + INTERVAL '10' DAY, 0);

INSERT INTO PHUONGTHUCTT (MaPT, TenPT) VALUES ('COD', 'Thanh toán khi nhận hàng');
INSERT INTO PHUONGTHUCTT (MaPT, TenPT) VALUES ('BANK', 'Chuyển khoản ngân hàng');
INSERT INTO PHUONGTHUCTT (MaPT, TenPT) VALUES ('EWALLET', 'Ví điện tử');
INSERT INTO PHUONGTHUCTT (MaPT, TenPT) VALUES ('MOMO', 'Ví MoMo');
INSERT INTO PHUONGTHUCTT (MaPT, TenPT) VALUES ('CREDIT_CARD', 'Thẻ tín dụng / ghi nợ');

INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, NULL, CURRENT_TIMESTAMP - INTERVAL '6' DAY, 1, 90000, 0, 90000, 'PENDING', NULL, 'Đơn chờ xác nhận để test khách hủy trực tiếp');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, 2, CURRENT_TIMESTAMP - INTERVAL '5' DAY, 2, 76000, 0, 76000, 'CONFIRMED', NULL, 'Đơn đã xác nhận để test yêu cầu hủy');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, 2, CURRENT_TIMESTAMP - INTERVAL '4' DAY, 3, 121000, 10000, 111000, 'SHIPPING', 1, 'Đơn đang giao để test xác nhận đã nhận hàng');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, 2, CURRENT_TIMESTAMP - INTERVAL '3' DAY, 4, 45000, 0, 45000, 'DELIVERED', NULL, 'Đơn đã giao, đã có đánh giá sẵn');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, NULL, CURRENT_TIMESTAMP - INTERVAL '2' DAY, 5, 15000, 0, 15000, 'CANCELLED', NULL, 'Đơn đã hủy để test lịch sử đơn hàng');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (6, 2, CURRENT_TIMESTAMP - INTERVAL '14' DAY, 1, 38000, 0, 38000, 'DELIVERED', NULL, 'Seed review mon 1');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (7, 2, CURRENT_TIMESTAMP - INTERVAL '14' DAY, 2, 36000, 0, 36000, 'DELIVERED', NULL, 'Seed review mon 2');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (8, 2, CURRENT_TIMESTAMP - INTERVAL '13' DAY, 3, 42000, 0, 42000, 'DELIVERED', NULL, 'Seed review mon 3');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (9, 2, CURRENT_TIMESTAMP - INTERVAL '13' DAY, 4, 42000, 0, 42000, 'DELIVERED', NULL, 'Seed review mon 4');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (10, 2, CURRENT_TIMESTAMP - INTERVAL '12' DAY, 5, 35000, 0, 35000, 'DELIVERED', NULL, 'Seed review mon 5');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, 2, CURRENT_TIMESTAMP - INTERVAL '12' DAY, 1, 45000, 0, 45000, 'DELIVERED', NULL, 'Seed review mon 6');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (6, 2, CURRENT_TIMESTAMP - INTERVAL '11' DAY, 2, 40000, 0, 40000, 'DELIVERED', NULL, 'Seed review mon 7');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (7, 2, CURRENT_TIMESTAMP - INTERVAL '11' DAY, 3, 45000, 0, 45000, 'DELIVERED', NULL, 'Seed review mon 8');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (8, 2, CURRENT_TIMESTAMP - INTERVAL '10' DAY, 4, 65000, 0, 65000, 'DELIVERED', NULL, 'Seed review mon 9');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (9, 2, CURRENT_TIMESTAMP - INTERVAL '10' DAY, 5, 40000, 0, 40000, 'DELIVERED', NULL, 'Seed review mon 10');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (10, 2, CURRENT_TIMESTAMP - INTERVAL '9' DAY, 1, 35000, 0, 35000, 'DELIVERED', NULL, 'Seed review mon 11');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, 2, CURRENT_TIMESTAMP - INTERVAL '9' DAY, 2, 20000, 0, 20000, 'DELIVERED', NULL, 'Seed review mon 12');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (6, 2, CURRENT_TIMESTAMP - INTERVAL '8' DAY, 3, 28000, 0, 28000, 'DELIVERED', NULL, 'Seed review mon 13');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (7, 2, CURRENT_TIMESTAMP - INTERVAL '8' DAY, 4, 15000, 0, 15000, 'DELIVERED', NULL, 'Seed review mon 14');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (8, 2, CURRENT_TIMESTAMP - INTERVAL '7' DAY, 5, 20000, 0, 20000, 'DELIVERED', NULL, 'Seed review mon 15');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (9, 2, CURRENT_TIMESTAMP - INTERVAL '7' DAY, 1, 20000, 0, 20000, 'DELIVERED', NULL, 'Seed review mon 16');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (10, 2, CURRENT_TIMESTAMP - INTERVAL '6' DAY, 2, 12000, 0, 12000, 'DELIVERED', NULL, 'Seed review mon 17');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, 2, CURRENT_TIMESTAMP - INTERVAL '6' DAY, 3, 12000, 0, 12000, 'DELIVERED', NULL, 'Seed review mon 18');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (6, 2, CURRENT_TIMESTAMP - INTERVAL '5' DAY, 4, 12000, 0, 12000, 'DELIVERED', NULL, 'Seed review mon 19');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (7, 2, CURRENT_TIMESTAMP - INTERVAL '5' DAY, 5, 20000, 0, 20000, 'DELIVERED', NULL, 'Seed review mon 20');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (8, 2, CURRENT_TIMESTAMP - INTERVAL '4' DAY, 1, 8000, 0, 8000, 'DELIVERED', NULL, 'Seed review mon 21');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (9, 2, CURRENT_TIMESTAMP - INTERVAL '4' DAY, 2, 15000, 0, 15000, 'DELIVERED', NULL, 'Seed review mon 22');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (10, 2, CURRENT_TIMESTAMP - INTERVAL '3' DAY, 3, 20000, 0, 20000, 'DELIVERED', NULL, 'Seed review mon 23');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (6, 2, CURRENT_TIMESTAMP - INTERVAL '3' DAY, 4, 15000, 0, 15000, 'DELIVERED', NULL, 'Seed review mon 24');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (7, 2, CURRENT_TIMESTAMP - INTERVAL '2' DAY, 5, 15000, 0, 15000, 'DELIVERED', NULL, 'Seed review mon 25');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (8, 2, CURRENT_TIMESTAMP - INTERVAL '2' DAY, 1, 7000, 0, 7000, 'DELIVERED', NULL, 'Seed review mon 26');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (9, 2, CURRENT_TIMESTAMP - INTERVAL '1' DAY, 2, 5000, 0, 5000, 'DELIVERED', NULL, 'Seed review mon 27');
INSERT INTO DONHANG (MaTK_KH, MaTK_NV, NgayDat, MaDC, TongTienMon, TienGiamGia, ThanhTien, TrangThaiDon, MaGG, GhiChu) VALUES (1, 2, CURRENT_TIMESTAMP - INTERVAL '1' DAY, 3, 42000, 0, 42000, 'DELIVERED', NULL, 'Đơn đã giao nhưng chưa có đánh giá để test tạo mới');

INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (1, 6, 'Burger Bo Pho Mai', 2, 45000, 90000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (2, 1, 'Ga Ran Gion Cay', 2, 38000, 76000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (3, 6, 'Burger Bo Pho Mai', 1, 45000, 45000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (3, 1, 'Ga Ran Gion Cay', 2, 38000, 76000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (4, 6, 'Burger Bo Pho Mai', 1, 45000, 45000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (5, 24, 'Kem Sundae Dau', 1, 15000, 15000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (6, 1, 'Ga Ran Gion Cay', 1, 38000, 38000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (7, 2, 'Ga Ran Truyen Thong', 1, 36000, 36000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (8, 3, 'Ga Phu Sot Pho Mai', 1, 42000, 42000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (9, 4, 'Ga Sot Cay Ngot Han Quoc', 1, 42000, 42000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (10, 5, 'Ga Popcorn', 1, 35000, 35000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (11, 6, 'Burger Bo Pho Mai', 1, 45000, 45000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (12, 7, 'Burger Ga Gion Cay', 1, 40000, 40000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (13, 8, 'Burger Ca Tartar', 1, 45000, 45000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (14, 9, 'Burger Bo Gap Doi', 1, 65000, 65000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (15, 10, 'Mi Y Sot Bo Bam', 1, 40000, 40000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (16, 11, 'Mi Y Xuc Xich', 1, 35000, 35000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (17, 12, 'Khoai Tay Chien (Vua)', 1, 20000, 20000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (18, 13, 'Khoai Tay Lac Pho Mai', 1, 28000, 28000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (19, 14, 'Salad Bap Cai Dua Tuoi', 1, 15000, 15000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (20, 15, 'Tra Chanh Hat Chia', 1, 20000, 20000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (21, 16, 'Nuoc Ep Xoai Dao', 1, 20000, 20000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (22, 17, 'Pepsi', 1, 12000, 12000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (23, 18, 'Mirinda', 1, 12000, 12000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (24, 19, '7Up', 1, 12000, 12000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (25, 20, 'Cacao Sua Da', 1, 20000, 20000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (26, 21, 'Nuoc Suoi', 1, 8000, 8000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (27, 22, 'Banh Xoai Dao', 1, 15000, 15000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (28, 23, 'Tropical Sundae', 1, 20000, 20000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (29, 24, 'Kem Sundae Dau', 1, 15000, 15000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (30, 25, 'Kem Sundae Socola', 1, 15000, 15000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (31, 26, 'Kem Socola', 1, 7000, 7000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (32, 27, 'Kem Sua Tuoi', 1, 5000, 5000);
INSERT INTO CHITIETDH (MaDH, MaMon, TenMon, SoLuong, DonGia, ThanhTien) VALUES (33, 3, 'Ga Phu Sot Pho Mai', 1, 42000, 42000);

INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (1, 'COD', CURRENT_TIMESTAMP - INTERVAL '6' DAY, 90000, 'Pending');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (2, 'COD', CURRENT_TIMESTAMP - INTERVAL '5' DAY, 76000, 'Pending');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (3, 'BANK', CURRENT_TIMESTAMP - INTERVAL '4' DAY, 111000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (4, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '3' DAY, 45000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (5, 'COD', CURRENT_TIMESTAMP - INTERVAL '2' DAY, 15000, 'Cancelled');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (6, 'COD', CURRENT_TIMESTAMP - INTERVAL '14' DAY, 38000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (7, 'BANK', CURRENT_TIMESTAMP - INTERVAL '14' DAY, 36000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (8, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '13' DAY, 42000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (9, 'COD', CURRENT_TIMESTAMP - INTERVAL '13' DAY, 42000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (10, 'BANK', CURRENT_TIMESTAMP - INTERVAL '12' DAY, 35000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (11, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '12' DAY, 45000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (12, 'COD', CURRENT_TIMESTAMP - INTERVAL '11' DAY, 40000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (13, 'BANK', CURRENT_TIMESTAMP - INTERVAL '11' DAY, 45000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (14, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '10' DAY, 65000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (15, 'COD', CURRENT_TIMESTAMP - INTERVAL '10' DAY, 40000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (16, 'BANK', CURRENT_TIMESTAMP - INTERVAL '9' DAY, 35000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (17, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '9' DAY, 20000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (18, 'COD', CURRENT_TIMESTAMP - INTERVAL '8' DAY, 28000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (19, 'BANK', CURRENT_TIMESTAMP - INTERVAL '8' DAY, 15000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (20, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '7' DAY, 20000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (21, 'COD', CURRENT_TIMESTAMP - INTERVAL '7' DAY, 20000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (22, 'BANK', CURRENT_TIMESTAMP - INTERVAL '6' DAY, 12000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (23, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '6' DAY, 12000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (24, 'COD', CURRENT_TIMESTAMP - INTERVAL '5' DAY, 12000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (25, 'BANK', CURRENT_TIMESTAMP - INTERVAL '5' DAY, 20000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (26, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '4' DAY, 8000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (27, 'COD', CURRENT_TIMESTAMP - INTERVAL '4' DAY, 15000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (28, 'BANK', CURRENT_TIMESTAMP - INTERVAL '3' DAY, 20000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (29, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '3' DAY, 15000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (30, 'COD', CURRENT_TIMESTAMP - INTERVAL '2' DAY, 15000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (31, 'BANK', CURRENT_TIMESTAMP - INTERVAL '2' DAY, 7000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (32, 'MOMO', CURRENT_TIMESTAMP - INTERVAL '1' DAY, 5000, 'Paid');
INSERT INTO THANHTOAN (MaDH, MaPT, NgayTT, SoTien, TrangThaiTT) VALUES (33, 'COD', CURRENT_TIMESTAMP - INTERVAL '1' DAY, 42000, 'Paid');

INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (6, 1, 6, 5, '.', CURRENT_TIMESTAMP - INTERVAL '13' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (7, 2, 7, 4, '.', CURRENT_TIMESTAMP - INTERVAL '13' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (8, 3, 8, 5, '.', CURRENT_TIMESTAMP - INTERVAL '12' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (9, 4, 9, 4, '.', CURRENT_TIMESTAMP - INTERVAL '12' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (10, 5, 10, 5, '.', CURRENT_TIMESTAMP - INTERVAL '11' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (1, 6, 11, 5, '.', CURRENT_TIMESTAMP - INTERVAL '11' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (6, 7, 12, 4, '.', CURRENT_TIMESTAMP - INTERVAL '10' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (7, 8, 13, 4, '.', CURRENT_TIMESTAMP - INTERVAL '10' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (8, 9, 14, 5, '.', CURRENT_TIMESTAMP - INTERVAL '9' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (9, 10, 15, 5, '.', CURRENT_TIMESTAMP - INTERVAL '9' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (10, 11, 16, 4, '.', CURRENT_TIMESTAMP - INTERVAL '8' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (1, 12, 17, 5, '.', CURRENT_TIMESTAMP - INTERVAL '8' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (6, 13, 18, 5, '.', CURRENT_TIMESTAMP - INTERVAL '7' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (7, 14, 19, 4, '.', CURRENT_TIMESTAMP - INTERVAL '7' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (8, 15, 20, 4, '.', CURRENT_TIMESTAMP - INTERVAL '6' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (9, 16, 21, 5, '.', CURRENT_TIMESTAMP - INTERVAL '6' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (10, 17, 22, 4, '.', CURRENT_TIMESTAMP - INTERVAL '5' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (1, 18, 23, 4, '.', CURRENT_TIMESTAMP - INTERVAL '5' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (6, 19, 24, 4, '.', CURRENT_TIMESTAMP - INTERVAL '4' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (7, 20, 25, 5, '.', CURRENT_TIMESTAMP - INTERVAL '4' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (8, 21, 26, 4, '.', CURRENT_TIMESTAMP - INTERVAL '3' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (9, 22, 27, 5, '.', CURRENT_TIMESTAMP - INTERVAL '3' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (10, 23, 28, 4, '.', CURRENT_TIMESTAMP - INTERVAL '2' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (6, 24, 29, 5, '.', CURRENT_TIMESTAMP - INTERVAL '2' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (7, 25, 30, 4, '.', CURRENT_TIMESTAMP - INTERVAL '1' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (8, 26, 31, 5, '.', CURRENT_TIMESTAMP - INTERVAL '1' DAY);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (9, 27, 32, 5, '.', CURRENT_TIMESTAMP - INTERVAL '12' HOUR);
INSERT INTO DANHGIA (MaTK_KH, MaMon, MaDH, Sao, NoiDung, NgayDG) VALUES (1, 6, 4, 5, '.', CURRENT_TIMESTAMP - INTERVAL '2' DAY);

COMMIT;
